// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: threatlog.proto

package threatlogpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThreatLogService_LogEvent_FullMethodName = "/threatlog.ThreatLogService/LogEvent"
)

// ThreatLogServiceClient is the client API for ThreatLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio ThreatLog
type ThreatLogServiceClient interface {
	LogEvent(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
}

type threatLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThreatLogServiceClient(cc grpc.ClientConnInterface) ThreatLogServiceClient {
	return &threatLogServiceClient{cc}
}

func (c *threatLogServiceClient) LogEvent(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, ThreatLogService_LogEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThreatLogServiceServer is the server API for ThreatLogService service.
// All implementations must embed UnimplementedThreatLogServiceServer
// for forward compatibility.
//
// Servicio ThreatLog
type ThreatLogServiceServer interface {
	LogEvent(context.Context, *LogRequest) (*LogResponse, error)
	mustEmbedUnimplementedThreatLogServiceServer()
}

// UnimplementedThreatLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThreatLogServiceServer struct{}

func (UnimplementedThreatLogServiceServer) LogEvent(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogEvent not implemented")
}
func (UnimplementedThreatLogServiceServer) mustEmbedUnimplementedThreatLogServiceServer() {}
func (UnimplementedThreatLogServiceServer) testEmbeddedByValue()                          {}

// UnsafeThreatLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThreatLogServiceServer will
// result in compilation errors.
type UnsafeThreatLogServiceServer interface {
	mustEmbedUnimplementedThreatLogServiceServer()
}

func RegisterThreatLogServiceServer(s grpc.ServiceRegistrar, srv ThreatLogServiceServer) {
	// If the following call pancis, it indicates UnimplementedThreatLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThreatLogService_ServiceDesc, srv)
}

func _ThreatLogService_LogEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatLogServiceServer).LogEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreatLogService_LogEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatLogServiceServer).LogEvent(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThreatLogService_ServiceDesc is the grpc.ServiceDesc for ThreatLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThreatLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "threatlog.ThreatLogService",
	HandlerType: (*ThreatLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogEvent",
			Handler:    _ThreatLogService_LogEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "threatlog.proto",
}
