version: "3.9"

services:
  consul:
    image: consul:1.15.4
    container_name: consul
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - backend

  auth-service:
    build:
      context: .               
      dockerfile: ./auth-service/Dockerfile
    container_name: auth-service
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    ports:
      - "8080:8080"
    networks:
      - backend

  threatlog-service:
    build:
      context: .                
      dockerfile: ./threatlog-service/Dockerfile
    container_name: threatlog-service
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    ports:
      - "8081:8081"
    networks:
      - backend

  web:
    image: nginx:alpine
    container_name: web-ui
    volumes:
      - ./web:/usr/share/nginx/html:ro
    ports:
      - "8082:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
